version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "passless-solution"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1q0hm6z5femfm"
s3_prefix = "passless-solution"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
parameter_overrides = "UserPoolName=\"PassLessUserPool\" SESFromAddress=\"niloy369@gmail.com\""
